### PR TITLE
Adding support for cross-building against 2.11.

### PR DESCRIPTION
**Pull request by jsuereth**
- Fix/document tests.
  - Add difflib to run diffs by hand
  - Check changes to see if it's related to directory layout of examples vs. generated
  - Attempt to display nicer diffs on error.
- Add cross-source support for 2.10->2.11 and even binary-version directories.
- Make sure 2.10 tests pass.

2.11 tests still broken, cc @retronym / @gkossakowski

### CODE REVIEW

**Comment by retronym** [comment]
I wonder if I could call in a favour from @som-snytt on this one.

IIRC, the breaking change was https://github.com/scala/scala/commit/3f0a90bd53cd1fc85891cf2673318c3a91f713bc

In which some "extension points" in ScalaDoc's `UnitParser` were shuffled around a little.

We have to compensate for that shuffling somehow down here in `browse`.

Ideally we can just do this in a source compatible way for 2.10 and 2.11 (cut-n-paste allowed). Otherwise, we can use Josh's feats of build gymnastics herein to cross build with different sources.

**Comment by som-snytt** [comment]
Sure, I'll try to get caught up on the history, or pre-history.  It's a favo[u]r to me just to muck around in someone else's code.

**Comment by jsuereth** [comment]
ping!

**Comment by som-snytt** [comment]
OK, pung.

**Comment by retronym** [comment]
I took a bit of a look at this and it was a bit more complicated than I thought. The parser was [refactored](https://github.com/scala/scala/commit/3d5c675982803e3a17262245a05266b2f5b64bc3#diff-0023b3bfa053fb16603156b785efa7adL519) in a way that made it hard to find out when we're in a a non-doc comment. The failing tests in this project are because comments are no longer highlighted as such in the HTML output.

**Comment by som-snytt** [comment]
I also bit.  The first problem I saw was that keywords were rearranged, so range test on the token id broke.  Just to let you know I was punged but not expunged.

**Comment by jsuereth** [comment]
Ok, so need to follow up on this PR.  We're rapidly approaching needing a owrking 2.11 build.  I'm ok merging a borked 2.11 build if 2.10 works for now, and cleaning up 2.11 in a follow-on PR.  @retronym wdyt of the changes otherwise?

**Comment by retronym** [comment]
My recommendation is to disable SXR on the 2.11 branch of SBT. Changes to the Scala parser in 2.11 mean the undocumented extension points that SXR uses to be notified of comments are gone, and it isn't clear if we can workaround them. The principled fix is to change the compiler to re-add these hooks, but even that eluded me when I tried.

**Comment by gkossakowski** [comment]
Should this PR be dropped?

**Comment by eed3si9n** [comment]
Closing this in favor of #3

**Pull request closed without merging**
